# Generated by Django 5.0.6 on 2024-07-04 11:48

import accounts.utility
import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('account_type', models.CharField(choices=[('S', 'SAVINGS'), ('C', 'CURRENT'), ('D', 'DOM')], default='S', max_length=8)),
                ('account_number', models.CharField(default=accounts.utility.generate_acct_number, max_length=10, primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('pin', models.CharField(max_length=4, validators=[accounts.validators.validate_pin])),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('CREDIT', 'CRE'), ('DEBIT', 'DEB'), ('TRANSFER', 'TRA'), ('WITHDRAW', 'WITH')], default='CREDIT', max_length=8)),
                ('transaction_time', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('description', models.TextField()),
                ('transaction_status', models.CharField(choices=[('P', 'PENDING'), ('S', 'SUCCESSFUL'), ('F', 'FAILED')], default='S', max_length=1)),
                ('transaction_id', models.CharField(default=accounts.utility.generate_acct_number, max_length=9)),
            ],
        ),
    ]
